setwd(choose.dir())
library(RCurl)
library(ROAuth)
library(twitteR)
library(stringr)
tweets = searchTwitter("AUSvBAN",n=1500)
tweets.text = laply(tweets, function(t)t$getText())
tweets.text <- iconv(tweets.text,"UTF-8")
write.csv(tweets.text, file = 'tweets.csv')
pos = scan('positive-words.txt',what='character',comment.char = ';')
neg = scan('negative-words.txt',what='character',comment.char = ';')
source('sentiment.r')
analysis = score.sentiment(tweets.text, pos, neg, .progress='none')
table(analysis$score)
hist(analysis$score)

